apiVersion: apps/v1

kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      hostPorts: true
      privileged: true
      automountServiceAccountToken: true # By Default
      # automountServiceAccountToken: false # Recommended
      securityContext:
        runAsUser: 0
      containers:
        - name: nginx
          image: nginx:1.14.2
          imagePullPolicy: IfNotPresent # By Default
         #imagePullPolicy: Always # Recommended
          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: true
            privileged: true
            readOnlyRootFilesystem: false
            procMount: Default
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]
            allowPrivilegeEscalation: true
            sysctls: []
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
            requests:
              cpu: 100m
              memory: 200Mi